include $(APPLECORE)/Common/Defs

TARGET=BWV.1030.3

ACC-DECLS=$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ach/BOOLEAN.ach:$(LIB-AC)/ac/GRAPHICS.ac:$(LIB-AC)/ac/TONES.ac:$(LIB-AC)/ach/PITCHES.440.EQUAL.ach

include $(COMMON)/Makefile.ac
