include $(APPLECORE)/Common/Defs

ACC-DECLS=$(LIB-ACH)/MON.ach:$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-ACH)/BOOLEAN.ach:$(LIB-AC)/ac/GRAPHICS.ac:$(LIB-AC)/ac/TONES.ac:$(LIB-ACH)/PITCHES.440.EQUAL.ach

include $(COMMON)/Makefile.ac
