include $(APPLECORE)/Common/Defs

ACC-DECLS=Include/ac/EVENTS.ac:Include/ac/PARSING.ac:Include/ac/ROOMS.ac:Include/ac/OBJECTS.ac:Include/ac/STATE.ac:$(LIB-AC)/IO.ac:$(LIB-AC)/STRING.ac:$(LIB-AC)/CHAR.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach:$(LIB-AC)/PRINT.WORDS.ac

include $(COMMON)/Makefile.ac.including

