include $(APPLECORE)/Defs.common

TARGET=MINI.ADVENTURE

ACC-DECLS=Include/ac/MA.EVENTS.ac:Include/ac/MA.PARSING.ac:Include/ac/MA.ROOMS.ac:Include/ac/MA.OBJECTS.1.ac:Include/ac/MA.OBJECTS.2.ac:Include/ac/MA.STATE.ac:$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ach/BOOLEAN.ach:$(LIB-AC)/ac/PRINT.WORDS.ac

include $(APPLECORE)/Makefile.ac.including.common

