include $(APPLECORE)/Defs.common

TARGET=ARTIST

ACC-DECLS=$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ach/BOOLEAN.ach:$(LIB-AC)/ac/GRAPHICS.ac:$(LIB-AC)/ac/PRINT.WORDS.ac:Include/ac/ARTIST.1.ac:Include/ac/ARTIST.2.ac

include $(APPLECORE)/Makefile.ac.including.common
