LIB=../../../Lib
DECLS=${LIB}/ach/MON.ach:${LIB}/ac/IO.ac:${LIB}/ac/DOS.ac
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -tf=HELLO.OBJ,D1 -avm-drive=2 -origin=8192

include ${APPLECORE}/Makefile.ac.common

