LIBS=${APPLECORE}/Lib/avm:${APPLECORE}/Lib-AVM/avm
RUNTIME=${APPLECORE}/Runtime/avm
SC-AVM-ASM = ${APPLECORE}/Assembler/bin/sc-avm-asm -i ${LIBS}:${RUNTIME}:../ac/avm -d obj ${OPTS}
TARGET=CHAIN

include ${APPLECORE}/Makefile.avm.common

