LIB=../../../../Lib
DECLS=${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach:${LIB}/ac/GRAPHICS.ac:${LIB}/ac/PRINT.WORDS.ac:ac/MASTERMIND.1.ac:ac/MASTERMIND.2.ac
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../../Makefile.ac.common
