SC-AVM-ASM = ${APPLECORE}/Assembler/bin/sc-avm-asm -i ${APPLECORE}/Lib/avm:${APPLECORE}/Lib-AVM/avm:${APPLECORE}/Runtime/avm:avm -d obj ${OPTS}

TARGET=SHELL.EDITOR

include ${APPLECORE}/Makefile.avm.common.2


