include ${APPLECORE}/Defs.common

DECLS=${LIB-AC}/ach/MON.ach:${LIB-AC}/ac/IO.ac:ac/MASTER.ac:ac/CHAIN.PROGRAM.1.ac:ac/CHAIN.PROGRAM.2.ac
ACC += -decls=${DECLS} -include

include ${APPLECORE}/Makefile.ac.common

