LIB=../../../Lib
DECLS=../ac/MINI.ADVENTURE.ac:ac/MA.EVENTS.ac:ac/MA.PARSING.ac:ac/MA.ROOMS.ac:ac/MA.OBJECTS.1.ac:ac/MA.OBJECTS.2.ac:ac/MA.OBJECTS.3.ac:ac/MA.VERBS.1.ac:ac/MA.VERBS.2.ac:ac/MA.VERBS.3.ac:ac/MA.COMMANDS.ac:ac/MA.STATE.ac:${LIB}/ac/PRINT.WORDS.ac:${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../Makefile.ac.common
