LIB=../../../Lib
DECLS=../ac/MINI.ADVENTURE.ac:ac/MA.PARSING.ac:ac/MA.ROOMS.ac:ac/MA.OBJECTS.ac:ac/MA.VERBS.ac:ac/MA.COMMANDS.ac:${LIB}/ac/PRINT.WORDS.ac:${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../Makefile.ac.common
