include $(APPLECORE)/Defs.common

ACC-DECLS=$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ach/BOOLEAN.ach:$(LIB-AC)/ac/GRAPHICS.ac:$(LIB-AC)/ac/STRING.ac

include $(APPLECORE)/Makefile.ac.several.common
