include $(APPLECORE)/Common/Defs

ACC-DECLS=ac/EDIFY.INPUT.ac:ac/EDIFY.HANDLERS.ac:ac/EDIFY.BUFFER.ac:ac/EDIFY.DISK.ac:$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/DOS.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-AC)/ac/COPY.ac:$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ach/BOOLEAN.ach

include $(COMMON)/Makefile.ac.included
