LIB=${APPLECORE}/Lib
DECLS=ac/EDIFY.INPUT.ac:ac/EDIFY.HANDLERS.ac:ac/EDIFY.BUFFER.ac:ac/EDIFY.DISK.ac:${LIB}/ac/IO.ac:${LIB}/ac/DOS.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ac/COPY.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ${APPLECORE}/Makefile.ac.common
