include $(APPLECORE)/Common/Defs

ACC-DECLS=ac/EDIFY.INPUT.ac:ac/EDIFY.HANDLERS.ac:ac/EDIFY.BUFFER.ac:ac/EDIFY.DISK.ac:$(LIB-AC)/IO.ac:$(LIB-AC)/DOS.ac:$(LIB-AC)/STRING.ac:$(LIB-AC)/CHAR.ac:$(LIB-AC)/COPY.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach

include $(COMMON)/Makefile.ac.included
