:NEW
* -------------------------------
* THE APPLECORE COMPILER, V1.0
* PROGRAM PROLOGUE
* -------------------------------
* REFERENCE LABELS
* -------------------------------
* STACK POINTER
ACC.SP	.EQ $00
* FRAME POINTER
ACC.FP	.EQ $02
* INDEX POINTER
ACC.IP	.EQ $04
* SIZE REG
ACC.SIZE .EQ $06
* GENERAL REG
ACC.GR .EQ $07
* INDEX REG 1
ACC.IDX.1 .EQ $08
* INDEX REG 2
ACC.IDX.2 .EQ $09
* BOUND ON SP
ACC.SP.BOUND .EQ $4A
* BASIC HIMEM
BASIC.HIMEM .EQ $4C
* DOS VECTOR FOR COLD RESTART 
DOS.COLD.START .EQ $3D3
* SAVE REGS
MON.SAVE	.EQ $FF4A
* RESTORE REGS
MON.RESTORE	.EQ $FF3F
* -------------------------------
* INIT SP, FP, AND SP BOUND
* -------------------------------
ACC.START
	LDA #ACC.STACK
	STA ACC.SP
	STA ACC.FP
	LDA /ACC.STACK
	STA ACC.SP+1
	STA ACC.FP+1
	LDA BASIC.HIMEM
	STA ACC.SP.BOUND
	LDA BASIC.HIMEM+1
	STA ACC.SP.BOUND+1

