include $(APPLECORE)/Common/Defs

# Generate native code
ACC += -native

ACC-DECLS=$(LIB-ACH)/MON.ach:$(LIB-AC)/IO.ac:$(LIB-AC)/STRING.ac:$(LIB-ACH)/BOOLEAN.ach:$(LIB-AC)/GRAPHICS.ac:$(LIB-AC)/TONES.ac:$(LIB-ACH)/PITCHES.440.EQUAL.ach

include $(COMMON)/Makefile.ac
