LIB=../../../Lib
DECLS=ac/EDIFY.1.ac:ac/EDIFY.2.ac:ac/EDIFY.HANDLERS.1.ac:ac/EDIFY.HANDLERS.2.ac:ac/EDIFY.BUFFER.ac:ac/EDIFY.DISK.ac:${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../Makefile.ac.common
