SC-AVM-ASM = ${APPLECORE}/Assembler/bin/sc-avm-asm -i ${APPLECORE}/Lib/avm:${APPLECORE}/Lib-AVM/avm:${APPLECORE}/Runtime/avm:../ac/avm -d obj ${OPTS}
TARGET=CHAIN

include ${APPLECORE}/Makefile.avm.common.2

