include ${APPLECORE}/Defs.common

TARGET=RODS.COLOR.PATTERN

ACC-DECLS=${LIB-AC}/ac/IO.ac:${LIB-AC}/ac/STRING.ac:${LIB-AC}/ac/CHAR.ac:${LIB-AC}/ach/MON.ach:${LIB-AC}/ach/BOOLEAN.ach:${LIB-AC}/ac/GRAPHICS.ac:${LIB-AC}/ac/PRINT.WORDS.ac:${LIB-AC}/ach/SOFT.SWITCHES.ach

SC-AVM-ASM += -i ../Assembly/avm

include ${APPLECORE}/Makefile.ac.common
