include $(APPLECORE)/Common/Defs

ACC-DECLS=$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach:$(LIB-AC)/ac/GRAPHICS.ac:$(LIB-AC)/ac/PRINT.WORDS.ac:$(LIB-ACH)/SOFT.SWITCHES.ach

SC-AVM-ASM += -i ../Assembly/avm

include $(COMMON)/Makefile.ac
