LIB=../../../Lib

DECLS=ac/BEAR.ac:ac/COMMANDS.ac:ac/DISK.ac:ac/MAIN.ac:ac/PARSING.ac:ac/MODULES.ac:ac/INVENTORY.ac:ac/ROOMS.ac:ac/ROOMS.0.ac:ac/ROOMS.1.ac:ac/ROOMS.2.ac:ac/OBJECTS.ac:ac/OBJECTS.0.ac:ac/VERBS.ac:ac/STATE.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach:${LIB}/ac/PRINT.WORDS.ac:${LIB}/ac/IO.ac:${LIB}/ac/DOS.ac:${LIB}/ac/COPY.ac

ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../Makefile.ac.common

