LIB=../../../Lib

DECLS=ac/COMMANDS.ac:ac/DISK.ac:ac/MAIN.ac:ac/PARSING.ac:ac/ROOMS.COMMON.ac:ac/ROOMS.0.ac:ac/STATE.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach:${LIB}/ac/PRINT.WORDS.ac:${LIB}/ac/IO.ac:${LIB}/ac/DOS.ac

ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../Makefile.ac.common
