LIB=../../../Lib
DECLS=${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach:${LIB}/ac/GRAPHICS.ac:${LIB}/ac/PRINT.WORDS.ac:ac/ARTIST.1.ac:ac/ARTIST.2.ac:../ac/ARTIST.ac:${LIB}/ac/DOS.ac:${LIB}/ac/COPY.ac
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ../../../Makefile.ac.common
