LIB=../../Lib
DECLS=${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach:${LIB}/ac/GRAPHICS.ac
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS}
include ../../Makefile.ac.common
