all:
	make -C HelloWorld
	make -C Hexconvert
	make -C MiniAdventure
	make -C Redbook
	make -C Tone
	make -C Artist
	make -C Chain
	make -C Edify
	make -C BelowTheBasement

clean:
	make -C HelloWorld clean
	make -C Hexconvert clean
	make -C MiniAdventure clean-include
	make -C Redbook clean
	make -C Tone clean
	make -C Artist clean-include
	make -C Chain clean
	make -C Edify clean-include
	make -C BelowTheBasement clean
