all:
	make -C Artist
	make -C BelowTheBasement
	make -C Chain
	make -C Edify
	make -C HelloWorld
	make -C Hexconvert
	make -C MiniAdventure
	make -C PixelEditor
	make -C Redbook
	make -C Tone

clean:
	make -C Artist clean
	make -C BelowTheBasement clean
	make -C Chain clean
	make -C Edify clean
	make -C HelloWorld clean
	make -C Hexconvert clean
	make -C MiniAdventure clean
	make -C PixelEditor clean
	make -C Redbook clean
	make -C Tone clean
