LIB=${APPLECORE}/Lib
DECLS=${LIB}/ach/MON.ach:${LIB}/ac/IO.ac:ac/MASTER.ac:ac/CHAIN.PROGRAM.1.ac:ac/CHAIN.PROGRAM.2.ac
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS} -include

include ${APPLECORE}/Makefile.ac.common

