include $(APPLECORE)/Common/Defs

ACC-DECLS=../ac/MINI.ADVENTURE.ac:ac/EVENTS.ac:ac/PARSING.ac:ac/ROOMS.ac:ac/OBJECTS.ac:ac/VERBS.ac:ac/COMMANDS.ac:ac/STATE.ac:$(LIB-AC)/PRINT.WORDS.ac:$(LIB-AC)/IO.ac:$(LIB-AC)/STRING.ac:$(LIB-AC)/CHAR.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach

include $(COMMON)/Makefile.ac.included
