include $(APPLECORE)/Common/Defs

ACC-DECLS=../ac/MINI.ADVENTURE.ac:ac/MA.EVENTS.ac:ac/MA.PARSING.ac:ac/MA.ROOMS.ac:ac/MA.OBJECTS.1.ac:ac/MA.OBJECTS.2.ac:ac/MA.OBJECTS.3.ac:ac/MA.VERBS.1.ac:ac/MA.VERBS.2.ac:ac/MA.VERBS.3.ac:ac/MA.COMMANDS.ac:ac/MA.STATE.ac:$(LIB-AC)/ac/PRINT.WORDS.ac:$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach

include $(COMMON)/Makefile.ac.included
