#
# Makefile for translating top-level AVM files, when there is no
# AppleCore source.
#

# AVM source files
SRCS += $(wildcard avm/*.avm)

# Add generated assembly files to include path
SC-AVM-ASM += -i ../AppleCore/avm:../AppleCore/Include/avm

# Build target file
obj : $(SRCS)
	rm -Rf $@
	mkdir $@
	make obj/$(TARGET).obj FILE=$(TARGET)

# Build one file avm/FILE.avm into obj/FILE.OBJ
obj/$(FILE).obj : avm/$(FILE).avm obj
	$(SC-AVM-ASM) avm/$(FILE).avm

clean :
	rm -Rf obj

.PHONY: clean
