#
# Makefile for translating top-level AVM files, when there is no
# AppleCore source.
#
SRCS     ?= $(wildcard avm/*.avm)

# Build all files avm/*.avm into obj/*.OBJ
obj : $(SRCS)
	rm -Rf $@
	mkdir $@
	$(MAKE_ALL) avm obj

# Build one file avm/FILE.avm into obj/FILE.OBJ
obj/$(FILE).obj : avm/$(FILE).avm obj
	$(SC-AVM-ASM) avm/$(FILE).avm

clean :
	rm -Rf obj

.PHONY: clean