include $(APPLECORE)/Common/Defs

ACC-DECLS=Include/ac/EDIFY.INPUT.ac:Include/ac/EDIFY.BUFFER.ac:$(LIB-AC)/IO.ac:$(LIB-AC)/STRING.ac:$(LIB-AC)/CHAR.ac:$(LIB-AC)/COPY.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach

include $(COMMON)/Makefile.ac.including


