include $(APPLECORE)/Common/Defs

ACC-DECLS=Include/ac/EDIFY.INPUT.ac:Include/ac/EDIFY.BUFFER.ac:$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-AC)/ac/COPY.ac:$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ach/BOOLEAN.ach

include $(COMMON)/Makefile.ac.including


