include $(APPLECORE)/Defs.common

TARGET=HEXCONVERT
ACC-DECLS=$(LIB-AC)/ac/IO.ac:$(LIB-AC)/ac/STRING.ac:$(LIB-AC)/ac/CHAR.ac:$(LIB-AC)/ach/MON.ach:$(LIB-AC)/ach/BOOLEAN.ach

include $(APPLECORE)/Makefile.ac.common
