LIB=../../Lib
INCLUDE=Include
DECLS=${INCLUDE}/ac/MA.PARSING.ac:${INCLUDE}/ac/MA.ROOMS.ac:${INCLUDE}/ac/MA.OBJECT.DATA.ac:${INCLUDE}/ac/MA.OBJECT.FNS.ac:${LIB}/ac/IO.ac:${LIB}/ac/STRING.ac:${LIB}/ac/CHAR.ac:${LIB}/ach/MON.ach:${LIB}/ach/BOOLEAN.ach:${LIB}/ac/PRINT.WORDS.ac
ACC = ${APPLECORE}/Compiler/bin/acc -decls=${DECLS}

include ../../Makefile.ac.common
