all : 
	make -C BootFP
	make -C BootINT
	make -C InstallINT
	make -C InstallFP
	make -C Editor

clean :
	make -C BootFP clean
	make -C BootINT clean
	make -C InstallINT clean
	make -C InstallFP clean
	make -C Editor clean

