include $(APPLECORE)/Common/Defs

ACC-DECLS=$(LIB-AC)/IO.ac:$(LIB-AC)/STRING.ac:$(LIB-AC)/CHAR.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach:$(LIB-AC)/GRAPHICS.ac:$(LIB-AC)/PRINT.WORDS.ac:ac/MASTERMIND.INCLUDE.ac

include $(COMMON)/Makefile.ac.included
