include ${APPLECORE}/Defs.common

ACC-DECLS=${LIB-AC}/ac/IO.ac:${LIB-AC}/ac/STRING.ac:${LIB-AC}/ac/CHAR.ac:${LIB-AC}/ach/MON.ach:${LIB-AC}/ach/BOOLEAN.ach:${LIB-AC}/ac/GRAPHICS.ac:${LIB-AC}/ac/PRINT.WORDS.ac:ac/MASTERMIND.INCLUDE.ac

include ${APPLECORE}/Makefile.ac.included.common
