include ${APPLECORE}/Defs.common

DECLS=${LIB-AC}/ac/IO.ac:${LIB-AC}/ac/STRING.ac:${LIB-AC}/ac/CHAR.ac:${LIB-AC}/ach/MON.ach:${LIB-AC}/ach/BOOLEAN.ach:${LIB-AC}/ac/GRAPHICS.ac:${LIB-AC}/ac/PRINT.WORDS.ac:ac/ARTIST.1.ac:ac/ARTIST.2.ac:../ac/ARTIST.ac:${LIB-AC}/ac/DOS.ac:${LIB-AC}/ac/COPY.ac

ACC += -decls=${DECLS} -include

include ${APPLECORE}/Makefile.ac.common
