include $(APPLECORE)/Common/Defs

ACC-DECLS=$(LIB-AC)/IO.ac:$(LIB-AC)/STRING.ac:$(LIB-AC)/CHAR.ac:$(LIB-ACH)/MON.ach:$(LIB-ACH)/BOOLEAN.ach:$(LIB-AC)/GRAPHICS.ac:$(LIB-AC)/PRINT.WORDS.ac:ac/ARTIST.1.ac:ac/ARTIST.2.ac:../ac/ARTIST.ac:$(LIB-AC)/DOS.ac:$(LIB-AC)/COPY.ac

include $(COMMON)/Makefile.ac.included
