include ${APPLECORE}/Defs.common

DECLS=ac/BEAR.ac:ac/COMMANDS.ac:ac/DISK.ac:ac/MAIN.ac:ac/PARSING.ac:ac/MODULES.ac:ac/INVENTORY.ac:ac/ROOMS.ac:ac/ROOMS.0.ac:ac/ROOMS.1.ac:ac/ROOMS.2.ac:ac/OBJECTS.ac:ac/OBJECTS.0.ac:ac/VERBS.ac:ac/STATE.ac:${LIB-AC}/ac/STRING.ac:${LIB-AC}/ac/CHAR.ac:${LIB-AC}/ach/MON.ach:${LIB-AC}/ach/BOOLEAN.ach:${LIB-AC}/ac/PRINT.WORDS.ac:${LIB-AC}/ac/IO.ac:${LIB-AC}/ac/DOS.ac:${LIB-AC}/ac/COPY.ac

ACC +=  -decls=${DECLS} -include

include ${APPLECORE}/Makefile.ac.common

