SC-AVM-ASM = ${APPLECORE}/Assembler/bin/sc-avm-asm -i ${APPLECORE}/Lib/avm:${APPLECORE}/Lib-AVM/avm:${APPLECORE}/Runtime/avm:avm:../Editor/avm -d obj ${OPTS}

TARGET=INSTALL.ROM.77

include ${APPLECORE}/Makefile.avm.common.2


